name = "discord-calendar"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
 
# Explicitly declare this as a script Worker with no assets
[build]
command = ""
 